ALTER TABLE `#!-PREFIX-!#forums` ENGINE = InnoDB;
ALTER TABLE `#!-PREFIX-!#posts` ENGINE = InnoDB;
ALTER TABLE `#!-PREFIX-!#threads` ENGINE = InnoDB;
ALTER TABLE `#!-PREFIX-!#forums` ADD `timestamp_new` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#forums` CHANGE `timestamp_new` `timestamp_new` DATETIME NOT NULL;
UPDATE `#!-PREFIX-!#forums` SET `timestamp_new` = FROM_UNIXTIME(`timestamp`);
ALTER TABLE `#!-PREFIX-!#forums` DROP `timestamp`;
ALTER TABLE `#!-PREFIX-!#forums` CHANGE `timestamp_new` `timestamp` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#posts` ADD `timestamp_new` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#posts` CHANGE `timestamp_new` `timestamp_new` DATETIME NOT NULL;
UPDATE `#!-PREFIX-!#posts` SET `timestamp_new` = FROM_UNIXTIME(`timestamp`);
ALTER TABLE `#!-PREFIX-!#posts` DROP `timestamp`;
ALTER TABLE `#!-PREFIX-!#posts` CHANGE `timestamp_new` `timestamp` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#posts` ADD `lastedit_new` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#posts` CHANGE `lastedit_new` `lastedit_new` DATETIME NOT NULL;
UPDATE `#!-PREFIX-!#posts` SET `lastedit_new` = FROM_UNIXTIME(`lastedit`);
ALTER TABLE `#!-PREFIX-!#posts` DROP `lastedit`;
ALTER TABLE `#!-PREFIX-!#posts` CHANGE `lastedit_new` `lastedit` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#threads` ADD `timestamp_new` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#threads` CHANGE `timestamp_new` `timestamp_new` DATETIME NOT NULL;
UPDATE `#!-PREFIX-!#threads` SET `timestamp_new` = FROM_UNIXTIME(`timestamp`);
ALTER TABLE `#!-PREFIX-!#threads` DROP `timestamp`;
ALTER TABLE `#!-PREFIX-!#threads` CHANGE `timestamp_new` `timestamp` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#threads` ADD `lastedit_new` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#threads` CHANGE `lastedit_new` `lastedit_new` DATETIME NOT NULL;
UPDATE `#!-PREFIX-!#threads` SET `lastedit_new` = FROM_UNIXTIME(`lastedit`);
ALTER TABLE `#!-PREFIX-!#threads` DROP `lastedit`;
ALTER TABLE `#!-PREFIX-!#threads` CHANGE `lastedit_new` `lastedit` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#threads` ADD `lastpost_new` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#threads` CHANGE `lastpost_new` `lastpost_new` DATETIME NOT NULL;
UPDATE `#!-PREFIX-!#threads` SET `lastpost_new` = FROM_UNIXTIME(`lastpost`);
ALTER TABLE `#!-PREFIX-!#threads` DROP `lastpost`;
ALTER TABLE `#!-PREFIX-!#threads` CHANGE `lastpost_new` `lastpost` DATETIME NOT NULL;
ALTER TABLE `#!-PREFIX-!#forums` ADD INDEX ( `userid` );
ALTER TABLE `#!-PREFIX-!#threads` ADD INDEX ( `forumid` );
ALTER TABLE `#!-PREFIX-!#threads` ADD INDEX ( `userid` );
ALTER TABLE `#!-PREFIX-!#posts` ADD INDEX ( `threadid` );
ALTER TABLE `#!-PREFIX-!#posts` ADD INDEX ( `userid` );
