DROP TABLE IF EXISTS `#!-PRÄFIX-!#right`;
CREATE TABLE `#!-PRÄFIX-!#right` (  `ID` int(10) NOT NULL AUTO_INCREMENT,  `level` varchar(100) COLLATE latin1_general_ci NOT NULL,   `right` varchar(120) COLLATE latin1_general_ci NOT NULL,  `ok` varchar(100) COLLATE latin1_general_ci NOT NULL,  `description` varchar(200) COLLATE latin1_general_ci NOT NULL,   PRIMARY KEY (`ID`)  ) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=93 ;
INSERT INTO `#!-PRÄFIX-!#right` VALUES(1, '1', 'adminsite', 'false', 'Erlaubnis zum Betreten der Administrationsseite');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(2, '1', 'newswrite', 'false', 'Erlaubnis zum Newsmeldungen schreiben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(3, '1', 'newsdel', 'false', 'Erlaubnis um Newsmeldungen zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(4, '1', 'newsedit', 'false', 'Erlaubnis um Newsmeldungen zu bearbeiten');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(5, '1', 'addvideo', 'false', 'Erlaubnis um Videos zur Videogallerie hinzuzufügen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(6, '1', 'delvideo', 'false', 'Erlaubnis um ein Video aus der Videogallerie zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(7, '1', 'useragree', 'false', 'Erlaubnis um ein Anwärter anzunehmen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(8, '1', 'userdisagree', 'false', 'Erlaubnis um ein Anwärter abzulehnen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(9, '1', 'upload', 'false', 'Erlaubnis um eine Datei in den DL-Bereich hochzuladen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(10, '1', 'userchangelevel', 'false', 'Erlaubnis um das Level eines Benutzers zu ändern');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(11, '1', 'userdelet', 'false', 'Erlaubnis um einen User zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(12, '1', 'readl1', 'true', 'Erlaubnis um Newsmeldungen des Level 1 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(13, '1', 'readl2', 'false', 'Erlaubnis um Newsmeldungen des Level 2 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(14, '1', 'readl3', 'false', 'Erlaubnis um Newsmeldungen des Level 3 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(15, '1', 'moduladmin', 'false', 'Das Recht Module zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(16, '1', 'manage_vote', 'false', 'Das Rechte Umfragen zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(17, '1', 'forum_nopassword', 'false', 'Forum: Darf Themen betrachten ohne das Passwort einzugeben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(18, '1', 'forum_edit_post', 'false', 'Forum: Darf Threads und Posts bearbeiten die nicht ihm gehören');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(19, '1', 'forum_canusetypes', 'false', 'Forum: Darf die Thread Typen verwenden: (Sticky, Announce)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(20, '1', 'forum_canclosethread', 'false', 'Forum: Darf Threads schließen. (<b>Keiner</b> kann schreiben)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(21, '1', 'forum_edit_forum', 'false', 'Forum: Darf Foren bearbeiten.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(22, '1', 'forum_del_forum', 'false', 'Forum: Darf komplette Foren löschen.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(23, '1', 'see_email', 'false', 'Das Recht die E-Mail Adresse in der user Seite einzusehen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(24, '2', 'adminsite', 'true', 'Erlaubnis zum Betreten der Administrationsseite');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(25, '2', 'newswrite', 'true', 'Erlaubnis zum Newsmeldungen schreiben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(26, '2', 'newsdel', 'true', 'Erlaubnis um Newsmeldungen zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(27, '2', 'newsedit', 'true', 'Erlaubnis um Newsmeldungen zu bearbeiten');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(28, '2', 'addvideo', 'false', 'Erlaubnis um Videos zur Videogallerie hinzuzufügen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(29, '2', 'delvideo', 'false', 'Erlaubnis um ein Video aus der Videogallerie zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(30, '2', 'useragree', 'false', 'Erlaubnis um ein Anwärter anzunehmen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(31, '2', 'userdisagree', 'false', 'Erlaubnis um ein Anwärter abzulehnen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(32, '2', 'upload', 'true', 'Erlaubnis um eine Datei in den DL-Bereich hochzuladen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(33, '2', 'userchangelevel', 'false', 'Erlaubnis um das Level eines Benutzers zu ändern');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(34, '2', 'userdelet', 'false', 'Erlaubnis um einen User zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(35, '2', 'readl1', 'true', 'Erlaubnis um Newsmeldungen des Level 1 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(36, '2', 'readl2', 'true', 'Erlaubnis um Newsmeldungen des Level 2 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(37, '2', 'readl3', 'false', 'Erlaubnis um Newsmeldungen des Level 3 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(38, '2', 'moduladmin', 'false', 'Das Recht Module zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(39, '2', 'manage_vote', 'false', 'Das Rechte Umfragen zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(40, '2', 'forum_nopassword', 'false', 'Forum: Darf Themen betrachten ohne das Passwort einzugeben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(41, '2', 'forum_edit_post', 'false', 'Forum: Darf Threads und Posts bearbeiten die nicht ihm gehören');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(42, '2', 'forum_canusetypes', 'false', 'Forum: Darf die Thread Typen verwenden: (Sticky, Announce)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(43, '2', 'forum_canclosethread', 'false', 'Forum: Darf Threads schließen. (<b>Keiner</b> kann schreiben)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(44, '2', 'forum_edit_forum', 'false', 'Forum: Darf Foren bearbeiten.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(45, '2', 'forum_del_forum', 'false', 'Forum: Darf komplette Foren löschen.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(46, '2', 'see_email', 'false', 'Das Recht die E-Mail Adresse in der user Seite einzusehen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(47, '3', 'adminsite', 'true', 'Erlaubnis zum Betreten der Administrationsseite');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(48, '3', 'newswrite', 'true', 'Erlaubnis zum Newsmeldungen schreiben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(49, '3', 'newsdel', 'true', 'Erlaubnis um Newsmeldungen zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(50, '3', 'newsedit', 'true', 'Erlaubnis um Newsmeldungen zu bearbeiten');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(51, '3', 'addvideo', 'true', 'Erlaubnis um Videos zur Videogallerie hinzuzufügen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(52, '3', 'delvideo', 'true', 'Erlaubnis um ein Video aus der Videogallerie zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(53, '3', 'useragree', 'true', 'Erlaubnis um ein Anwärter anzunehmen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(54, '3', 'userdisagree', 'true', 'Erlaubnis um ein Anwärter abzulehnen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(55, '3', 'upload', 'true', 'Erlaubnis um eine Datei in den DL-Bereich hochzuladen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(56, '3', 'userchangelevel', 'true', 'Erlaubnis um das Level eines Benutzers zu ändern');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(57, '3', 'userdelet', 'false', 'Erlaubnis um einen User zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(58, '3', 'readl1', 'true', 'Erlaubnis um Newsmeldungen des Level 1 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(59, '3', 'readl2', 'true', 'Erlaubnis um Newsmeldungen des Level 2 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(60, '3', 'readl3', 'true', 'Erlaubnis um Newsmeldungen des Level 3 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(61, '3', 'moduladmin', 'true', 'Das Recht Module zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(62, '3', 'manage_vote', 'false', 'Das Rechte Umfragen zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(63, '3', 'forum_nopassword', 'false', 'Forum: Darf Themen betrachten ohne das Passwort einzugeben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(64, '3', 'forum_edit_post', 'false', 'Forum: Darf Threads und Posts bearbeiten die nicht ihm gehören');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(65, '3', 'forum_canusetypes', 'false', 'Forum: Darf die Thread Typen verwenden: (Sticky, Announce)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(66, '3', 'forum_canclosethread', 'false', 'Forum: Darf Threads schließen. (<b>Keiner</b> kann schreiben)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(67, '3', 'forum_edit_forum', 'false', 'Forum: Darf Foren bearbeiten.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(68, '3', 'forum_del_forum', 'false', 'Forum: Darf komplette Foren löschen.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(69, '3', 'see_email', 'false', 'Das Recht die E-Mail Adresse in der user Seite einzusehen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(70, '4', 'adminsite', 'true', 'Erlaubnis zum Betreten der Administrationsseite');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(71, '4', 'newswrite', 'true', 'Erlaubnis zum Newsmeldungen schreiben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(72, '4', 'newsdel', 'true', 'Erlaubnis um Newsmeldungen zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(73, '4', 'newsedit', 'true', 'Erlaubnis um Newsmeldungen zu bearbeiten');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(74, '4', 'addvideo', 'true', 'Erlaubnis um Videos zur Videogallerie hinzuzufügen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(75, '4', 'delvideo', 'true', 'Erlaubnis um ein Video aus der Videogallerie zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(76, '4', 'useragree', 'true', 'Erlaubnis um ein Anwärter anzunehmen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(77, '4', 'userdisagree', 'true', 'Erlaubnis um ein Anwärter abzulehnen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(78, '4', 'upload', 'true', 'Erlaubnis um eine Datei in den DL-Bereich hochzuladen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(79, '4', 'userchangelevel', 'true', 'Erlaubnis um das Level eines Benutzers zu ändern');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(80, '4', 'userdelet', 'false', 'Erlaubnis um einen User zu löschen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(81, '4', 'readl1', 'true', 'Erlaubnis um Newsmeldungen des Level 1 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(82, '4', 'readl2', 'true', 'Erlaubnis um Newsmeldungen des Level 2 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(83, '4', 'readl3', 'true', 'Erlaubnis um Newsmeldungen des Level 3 zu lesen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(84, '4', 'moduladmin', 'true', 'Das Recht Module zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(85, '4', 'manage_vote', 'true', 'Das Rechte Umfragen zu Managen');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(86, '4', 'forum_nopassword', 'true', 'Forum: Darf Themen betrachten ohne das Passwort einzugeben');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(87, '4', 'forum_edit_post', 'true', 'Forum: Darf Threads und Posts bearbeiten die nicht ihm gehören');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(88, '4', 'forum_canusetypes', 'true', 'Forum: Darf die Thread Typen verwenden: (Sticky, Announce)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(89, '4', 'forum_canclosethread', 'true', 'Forum: Darf Threads schließen. (<b>Keiner</b> kann schreiben)');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(90, '4', 'forum_edit_forum', 'true', 'Forum: Darf Foren bearbeiten.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(91, '4', 'forum_del_forum', 'true', 'Forum: Darf komplette Foren löschen.');
INSERT INTO `#!-PRÄFIX-!#right` VALUES(92, '4', 'see_email', 'true', 'Das Recht die E-Mail Adresse in der user Seite einzusehen');