CREATE TABLE IF NOT EXISTS `#!-PRÄFIX-!#download_kat` (
`ID` INT( 100 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL ,
`level` VARCHAR( 100 ) NOT NULL ,
`description` TEXT NOT NULL ,
`picture` LONGBLOB NULL
) ENGINE = MYISAM
