
INSERT INTO `#!-PRÄFIX-!#lang` (`lang`, `word`, `wort`) VALUES
('de', 'wrotenews', 'Sollten Sie gerade eine Newsmeldung geschrieben haben, öffnen Sie in neues Fenster und loggen Sie sich ein.'),
('de', 'wrotenews2', 'Danach gehen Sie auf diese Seite zurück und drücken Aktualisieren!'),
('de', 'nodelnews', 'Sie dürfen keine Newsmeldungen löschen!'),
('de', 'nowritenews', 'Sie dürfen keine Newsmeldungen schreiben!'),
('de', 'questions-webmaster', 'Sollten Sie Fragen haben, wenden die sich an den Webmaster!'),
('de', 'delok', 'Erfolgreich gelöscht!'),
('de', 'error-del', 'Fehler beim Löschen:'),
('de', 'postok', 'Erfolgreich eingetragen'),
('de', 'error-post', 'Fehler beim eintragen der News-Meldung'),
('de', 'headline', 'Überschrift:'),
('de', 'editnews', 'News Bearbeiten'),
('de', 'upload', 'Dateien hochladen'),
('de', 'anwerter', 'Anwerter'),
('de', 'newnews', 'Neue Nachricht:'),
('de', 'post', 'Eintragen'),
('de', 'modulman', 'Modul Manager'),
('de', 'bewerbungen', 'Bewerbungen'),
('de', 'kberechacanwae', 'Sie haben nicht die nötige Berechtigung, um Anwärter aufzunehmen!'),
('de', 'kberechdeanwae', 'Sie haben nicht die nötige Berechtigung, um Anwärter abzulehnen!'),
('de', 'bewebungstext', 'Bewebungstext'),
('de', 'yes', 'Ja'),
('de', 'no', 'Nein'),
('de', 'notfound', '404 Die gewünschte Seite konnte nicht gefunden werden!'),
('de', 'userorpasswordwrong', 'keine Verbindung möglich. Benutzername oder Passwort sind falsch'),
('de', 'nodb', 'Die Datenbank existiert nicht.'),
('de', 'comments', 'Kommentare'),
('de', 'by', 'von'),
('de', 'noright', 'Sie haben nicht das Recht das zu tun!'),
('de', 'noright2', 'Sie haben nicht das Recht um hier zu sein!'),
('de', 'morenews', 'Weitere Nachrichten'),
('de', 'delet', 'Löschen'),
('de', 'send', 'Abschicken'),
('de', 'edit', 'Bearbeiten'),
('de', 'loggedas', 'Eingeloggt als:'),
('de', 'editprofile', 'Profil bearbeiten'),
('de', 'login', 'Loggen Sie sich bitte ein!'),
('de', 'register', 'Registrieren'),
('de', 'username', 'Benutzername'),
('de', 'password', 'Passwort'),
('de', 'loginbutt', 'Login'),
('de', 'loginfail', 'Kein Login möglich. Benutzername oder Passwort sind falsch!'),
('de', 'back', 'Zurück'),
('de', 'error', 'Fehler'),
('de', 'titel', 'Titel'),
('de', 'uploadedby', 'Hochgeladen von'),
('de', 'description', 'Beschreibung'),
('de', 'uploadedam', 'Hochgeladen am'),
('de', 'norightlookfile', 'Sie haben nicht das nötige level diese Datei herunter zo laden!'),
('de', 'absender', 'Absender'),
('de', 'betreff', 'Betreff'),
('de', 'für', 'Für'),
('de', 'von', 'Von'),
('de', 'empfänger', 'Empfänger'),
('de', 'text', 'Text'),
('de', 'gelesen', 'Gelesen'),
('de', 'newpm', 'Neue PM verfassen'),
('de', 'postausgang', 'Postausgang'),
('de', 'antworten', 'Antworten'),
('de', 'messagenotforyou', 'Diese Nachricht ist nicht für Sie bestimmt!'),
('de', 'cantdelmessage', 'Sie können diese Nachricht nicht Löschen!!'),
('de', 'doublepost', 'Doppelpost entdeckt!'),
('de', 'posterror', 'Fehler Melden'),
('de', 'error-login-profil', 'Sie müssen sich erst einloggen, bevor sie das Profil änder können!'),
('de', 'page-intern', 'Seiten intern'),
('de', 'avatar', 'Avatar'),
('de', 'changepw', 'Passwort ändern'),
('de', 'upload-picture', 'Bild hochladen'),
('de', 'persönliches', 'Persönliches'),
('de', 'telephone', 'Telefon oder Handy'),
('de', 'email', 'E-Mail Adresse'),
('de', 'wohnort', 'Wohnort'),
('de', 'ok', 'Bestätigen'),
('de', 'sonstiges', 'Sonstiges'),
('de', 'start', 'Start'),
('de', 'cpu', 'CPU'),
('de', 'ram', 'RAM'),
('de', 'graka', 'Grafik-Karte'),
('de', 'hdd', 'Festplatte(n)'),
('de', 'clan', 'Clan'),
('de', 'clanname', 'Clanname'),
('de', 'clantag', 'ClanTag'),
('de', 'clanhist', 'Clan History'),
('de', 'clanhp', 'Clan Homepage'),
('de', 'oldpw', 'Altes Passwort'),
('de', 'newpw', 'Neues Passwort'),
('de', 'repnewpw', 'Passwort bestätigen'),
('de', 'pwwrong_profil', 'Passwort falsch eingegeben'),
('de', 'ok_profil', 'Erfolgreich Aktualisiert'),
('de', 'notallfields', 'Es wurden nicht alle Pflichfelder ausgefüllt'),
('de', 'name', 'Name'),
('de', 'nachname', 'Nachname'),
('de', 'datum', 'Datum'),
('de', 'since', 'Seit'),
('de', 'rank', 'Rang'),
('de', 'nick', 'Nickname'),
('de', 'mail', 'E-Mail'),
('de', 'alter', 'Alter'),
('de', 'birthday', 'Geburtstag'),
('de', 'lastlogin', 'Letzter Login'),
('de', 'pm', 'PM schicken'),
('de', 'never', 'Niemals'),
('de', 'page', 'Seite'),
('eng', 'wrotenews', 'If you have just written a news report, open in new window and login to your account.'),
('eng', 'wrotenews2', 'Then go back to this page and press Update!'),
('eng', 'nodelnews', 'You are not allowed to delete news!'),
('eng', 'nowritenews', 'You are not allowed to write news!'),
('eng', 'questions-webmaster', 'If you have any questions, contact the the webmaster!'),
('eng', 'delok', 'Successfully deleted!'),
('eng', 'error-del', 'Error while deleting:'),
('eng', 'postok', 'Successfully registered'),
('eng', 'error-post', 'Error while posting'),
('eng', 'headline', 'Headline:'),
('eng', 'editnews', 'Edit News'),
('eng', 'upload', 'Upload file'),
('eng', 'anwerter', '	Awaiting Activation'),
('eng', 'newnews', 'Write News report:'),
('eng', 'post', 'Post'),
('eng', 'modulman', 'Modul Manager'),
('eng', 'bewerbungen', 'Applications'),
('eng', 'kberechacanwae', 'You do not have the required permissions to activate members!'),
('eng', 'kberechdeanwae', 'You do not have the necessary authority to reject members!'),
('eng', 'bewebungstext', 'Application'),
('eng', 'yes', 'yes'),
('eng', 'no', 'no'),
('eng', 'notfound', '404 The requestet page can not be found!'),
('eng', 'userorpasswordwrong', 'no connection possible! Username or Password wrong!'),
('eng', 'nodb', 'The Database do not exsist.'),
('eng', 'comments', 'Comments'),
('eng', 'by', 'by'),
('eng', 'noright', 'You are not allowed to do this!'),
('eng', 'noright2', 'You ae not allowed to be here!'),
('eng', 'morenews', 'More Articels'),
('eng', 'delet', 'delet'),
('eng', 'send', 'send'),
('eng', 'edit', 'edit'),
('eng', 'loggedas', 'Logged as:'),
('eng', 'editprofile', 'Edit Profile'),
('eng', 'login', 'Please Login!'),
('eng', 'register', 'Register'),
('eng', 'username', 'Username'),
('eng', 'password', 'Password'),
('eng', 'loginbutt', 'login'),
('eng', 'loginfail', 'Can`t Login, your Username or Password are wrong!'),
('eng', 'back', 'back'),
('eng', 'error', 'Error'),
('eng', 'titel', 'Titel'),
('eng', 'uploadedby', 'Uploaded by'),
('eng', 'description', 'Description'),
('eng', 'uploadedam', 'Uploaded'),
('eng', 'norightlookfile', 'You do not have the necessary level this download this file!'),
('eng', 'absender', 'Sender'),
('eng', 'betreff', 'Subject'),
('eng', 'für', 'For'),
('eng', 'von', 'By'),
('eng', 'empfänger', 'addressee'),
('eng', 'text', 'Text'),
('eng', 'gelesen', 'read'),
('eng', 'newpm', 'write new pm'),
('eng', 'postausgang', 'Outbox'),
('eng', 'antworten', 'Reply'),
('eng', 'messagenotforyou', 'This message is not intended for you!'),
('eng', 'cantdelmessage', 'You can not delete this message!!'),
('eng', 'doublepost', 'Double Post discovered!'),
('eng', 'posterror', 'Post Error Log'),
('eng', 'error-login-profil', 'You must login to change your profile!'),
('eng', 'page-intern', 'Page Intern'),
('eng', 'avatar', 'Avatar'),
('eng', 'changepw', 'Change Password'),
('eng', 'upload-picture', 'Upload Picture'),
('eng', 'persönliches', 'Personal'),
('eng', 'telephone', 'Telephone or mobile phone'),
('eng', 'email', 'E-Mail Adress'),
('eng', 'wohnort', 'Residence'),
('eng', 'ok', 'Confirm'),
('eng', 'sonstiges', 'Other'),
('eng', 'start', 'start'),
('eng', 'cpu', 'CPU'),
('eng', 'ram', 'RAM'),
('eng', 'graka', 'Graphics card'),
('eng', 'hdd', 'Hard Drive'),
('eng', 'clan', 'Clan'),
('eng', 'clanname', 'Clanname'),
('eng', 'clantag', 'ClanTag'),
('eng', 'clanhist', 'Clan History'),
('eng', 'clanhp', 'Clan Homepage'),
('eng', 'oldpw', 'Old Password'),
('eng', 'newpw', 'New Password'),
('eng', 'repnewpw', 'Confirm Password'),
('eng', 'pwwrong_profil', 'Password is entered incorrectly'),
('eng', 'ok_profil', 'Successfully Updated'),
('eng', 'notallfields', 'There were not filled in all mandatory fields'),
('eng', 'name', 'name'),
('eng', 'nachname', 'family name'),
('eng', 'datum', 'Date'),
('eng', 'since', 'Since'),
('eng', 'rank', 'Level'),
('eng', 'nick', 'Nickname'),
('eng', 'mail', 'E-Mail'),
('eng', 'alter', 'Age'),
('eng', 'birthday', 'Birthday'),
('eng', 'lastlogin', 'LAst Login'),
('eng', 'pm', 'Send PM'),
('eng', 'never', 'Never'),
('eng', 'page', 'Page');
