INSERT INTO `#!-PRÄFIX-!#right` (`ID`, `level`, `right`, `ok`, `description`) VALUES
(1, 1, 'adminsite', 'false', 'Erlaubnis zum Betreten der Administrationsseite'),
(2, 1, 'newswrite', 'false', 'Erlaubnis zum Newsmeldungen schreiben'),
(3, 1, 'newsdel', 'false', 'Erlaubnis um Newsmeldungen zu löschen'),
(4, 1, 'newsedit', 'false', 'Erlaubnis um Newsmeldungen zu bearbeiten'),
(5, 1, 'addvideo', 'false', 'Erlaubnis um Videos zur Videogallerie hinzuzufügen'),
(6, 1, 'delvideo', 'false', 'Erlaubnis um ein Video aus der Videogallerie zu löschen'),
(7, 1, 'useragree', 'false', 'Erlaubnis um ein Anwärter anzunehmen'),
(8, 1, 'userdisagree', 'false', 'Erlaubnis um ein Anwärter abzulehnen'),
(9, 1, 'upload', 'false', 'Erlaubnis um eine Datei in den DL-Bereich hochzuladen'),
(10, 1, 'userchangelevel', 'false', 'Erlaubnis um das Level eines Benutzers zu ändern'),
(11, 1, 'userdelet', 'false', 'Erlaubnis um einen User zu löschen'),
(12, 1, 'readl1', 'true', 'Erlaubnis um Newsmeldungen des Level 1 zu lesen'),
(13, 1, 'readl2', 'false', 'Erlaubnis um Newsmeldungen des Level 2 zu lesen'),
(14, 1, 'readl3', 'false', 'Erlaubnis um Newsmeldungen des Level 3 zu lesen'),
(15, 1, 'moduladmin', 'false', 'Das Recht Module zu Managen'),
(16, 2, 'adminsite', 'true', 'Erlaubnis zum Betreten der Administrationsseite'),
(17, 2, 'newswrite', 'true', 'Erlaubnis zum Newsmeldungen schreiben'),
(18, 2, 'newsdel', 'true', 'Erlaubnis um Newsmeldungen zu löschen'),
(19, 2, 'newsedit', 'true', 'Erlaubnis um Newsmeldungen zu bearbeiten'),
(20, 2, 'addvideo', 'false', 'Erlaubnis um Videos zur Videogallerie hinzuzufügen'),
(21, 2, 'delvideo', 'false', 'Erlaubnis um ein Video aus der Videogallerie zu löschen'),
(22, 2, 'useragree', 'false', 'Erlaubnis um ein Anwärter anzunehmen'),
(23, 2, 'userdisagree', 'false', 'Erlaubnis um ein Anwärter abzulehnen'),
(24, 2, 'upload', 'true', 'Erlaubnis um eine Datei in den DL-Bereich hochzuladen'),
(25, 2, 'userchangelevel', 'false', 'Erlaubnis um das Level eines Benutzers zu ändern'),
(26, 2, 'userdelet', 'false', 'Erlaubnis um einen User zu löschen'),
(27, 2, 'readl1', 'true', 'Erlaubnis um Newsmeldungen des Level 1 zu lesen'),
(28, 2, 'readl2', 'true', 'Erlaubnis um Newsmeldungen des Level 2 zu lesen'),
(29, 2, 'readl3', 'false', 'Erlaubnis um Newsmeldungen des Level 3 zu lesen'),
(30, 2, 'moduladmin', 'false', 'Das Recht Module zu Managen'),
(31, 3, 'adminsite', 'true', 'Erlaubnis zum Betreten der Administrationsseite'),
(32, 3, 'newswrite', 'true', 'Erlaubnis zum Newsmeldungen schreiben'),
(33, 3, 'newsdel', 'true', 'Erlaubnis um Newsmeldungen zu löschen'),
(34, 3, 'newsedit', 'true', 'Erlaubnis um Newsmeldungen zu bearbeiten'),
(35, 3, 'addvideo', 'true', 'Erlaubnis um Videos zur Videogallerie hinzuzufügen'),
(36, 3, 'delvideo', 'true', 'Erlaubnis um ein Video aus der Videogallerie zu löschen'),
(37, 3, 'useragree', 'true', 'Erlaubnis um ein Anwärter anzunehmen'),
(38, 3, 'userdisagree', 'true', 'Erlaubnis um ein Anwärter abzulehnen'),
(39, 3, 'upload', 'true', 'Erlaubnis um eine Datei in den DL-Bereich hochzuladen'),
(40, 3, 'userchangelevel', 'true', 'Erlaubnis um das Level eines Benutzers zu ändern'),
(41, 3, 'userdelet', 'false', 'Erlaubnis um einen User zu löschen'),
(42, 3, 'readl1', 'true', 'Erlaubnis um Newsmeldungen des Level 1 zu lesen'),
(43, 3, 'readl2', 'true', 'Erlaubnis um Newsmeldungen des Level 2 zu lesen'),
(44, 3, 'readl3', 'true', 'Erlaubnis um Newsmeldungen des Level 3 zu lesen'),
(45, 3, 'moduladmin', 'true', 'Das Recht Module zu Managen');
